const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8'),blocks=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)],data=Object.fromEntries(blocks.filter(b=>/application\/json/.test(b[1])).map(b=>[b[1].match(/id="([^"]+)"/)[1],b[2]]));
const context={document:{getElementById:id=>({textContent:data[id]})},structuredClone,Math:Object.create(Math),module:{exports:{}}};context.Math.random=()=>.5;vm.runInNewContext(blocks.find(b=>b[2].includes('const HH = (() =>'))[2],context);const H=context.module.exports,SD=JSON.parse(data.smogonSnapshot);
let checks=0;const eq=(a,b,m)=>{assert.deepStrictEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)),m);checks++;},ok=(v,m)=>{assert(v,m);checks++;},throws=(f,m)=>{assert.throws(f,/inválida|Duplas exige/,m);checks++;};
const P={kind:'pass'},A=(name,side=1,slot=0)=>({kind:'move',moveId:H.normalizeName(name),target:{side,slot}}),D=(a=P,b=P)=>({kind:'double',actions:[a,b]});
const move=name=>{const d=SD.moves[H.normalizeName(name)];return {id:H.normalizeName(name),name:d.name,type:d.type,category:d.category,power:d.basePower,accuracy:90,alwaysHits:true,active:true};};
const mon=(id,moves=['Tackle'],spe=100)=>({id,name:id,type1:'Normal',level:36,maxHp:1000,stats:{hp:1000,atk:100,def:100,spa:100,spd:100,spe},moves:moves.map(move)});
const allMoves=['Tackle','Growl','Swords Dance','Rock Slide','Earthquake','Surf','Protect','Wide Guard','Sucker Punch','Quick Attack','U-turn','Baton Pass','Helping Hand','Heal Pulse','Haze','Perish Song','Follow Me','Ally Switch','Spikes','Explosion','Overheat','Life Dew','After You','Quash'];
function game(system,reserves=2){const g=H.newGame([mon('A0',allMoves,130),mon('A1',allMoves,120),...Array.from({length:reserves},(_,i)=>mon('Ar'+i))],[mon('B0',allMoves,110),mon('B1',allMoves,100),...Array.from({length:reserves},(_,i)=>mon('Br'+i))],{format:'doubles',damageSystem:system});for(const x of H.battlerEntries(g))x.pokemon.moves=allMoves.map(move);return g;}
function resolve(g,a=D(),b=D()){H.resolve(g,a,b);ok(!Object.keys(g).some(k=>k.startsWith('_')),'Transient focus/queue/spread state is removed');}
for(const system of ['standard','matrix-v0.2']){
 let g=game(system);eq(g.activeSlots,[[0,1],[0,1]],'Two starting Pokémon per trainer');eq(H.reserves(g,0),[2,3],'Partner is never offered as reserve');eq(g.log.filter(x=>x.kind==='switch').length,4,'All four Pokémon enter');
 resolve(g,D(A('Tackle',1,0),A('Tackle',1,1)),D(A('Tackle',0,0),A('Tackle',0,1)));eq(g.turn,2,'One global round for four actions');for(const x of H.battlerEntries(g))ok(x.pokemon.hp<1000,'Each Pokémon attacks its chosen target');
 g=game(system);resolve(g,D(A('Tackle',1,1),P));eq(g.team[1][0].hp,1000,'Unselected target remains untouched');ok(g.team[1][1].hp<1000,'Second enemy can be targeted');
 g=game(system);resolve(g,D(A('Swords Dance'),P));ok(g.team[0][0].flags.matrixSwords||g.team[0][0].flags.swordsUntil,'Self move affects acting Pokémon');ok(!g.team[0][1].flags.matrixSwords&&!g.team[0][1].flags.swordsUntil,'Self move does not affect partner');
 g=game(system);resolve(g,D(A('Rock Slide'),P));eq(g.team[0][1].hp,1000,'Enemy-only area move protects own partner');ok(g.team[1].slice(0,2).every(p=>p.hp<1000),'Rock Slide hits both enemies');
 g=game(system);resolve(g,D(A('Earthquake'),P));eq(g.team[0][0].hp,1000,'Earthquake excludes user');for(const [s,i] of [[0,1],[1,0],[1,1]])ok(g.team[s][i].hp<1000,'Earthquake hits adjacent enemy/ally');
 g=game(system);resolve(g,D(A('Rock Slide'),P),D(A('Protect',0,0),P));eq(g.team[1][0].hp,1000,'Individual Protect blocks only its user');ok(g.team[1][1].hp<1000,'Unprotected partner still takes spread damage');
 g=game(system);resolve(g,D(A('Rock Slide'),P),D(A('Wide Guard',0,0),P));eq(g.team[1][0].hp,1000,'Wide Guard protects its user');eq(g.team[1][1].hp,1000,'Wide Guard protects partner');
 g=game(system);resolve(g,D(A('Overheat'),P));eq(H.stages(g.team[0][0],'spa'),-2,'A self-drop occurs exactly once');
 g=game(system);g.team[0][0].heldItem='Life Orb';resolve(g,D(A('Rock Slide'),P));eq(g.team[0][0].hp,900,'Life Orb costs only once for a spread move');
 g=game(system);resolve(g,D(A('Explosion'),P));eq(g.team[0][0].hp,0,'Explosion user faints');for(const [s,i]of [[0,1],[1,0],[1,1]])ok(g.team[s][i].hp<1000,'Explosion reaches all targets before user faints');
 g=game(system);H.setWeather(g,'rain');for(const x of H.battlerEntries(g)){x.pokemon.hp=500;x.pokemon.heldItem='Leftovers';x.pokemon.disabled.tackle=3;x.pokemon.status={id:'burn'};}resolve(g);for(const x of H.battlerEntries(g)){eq(x.pokemon.hp,560,'Burn and Leftovers tick once for every active');eq(x.pokemon.disabled.tackle,2,'Disable timer ticks once');}eq(g.weather.turns,4,'Shared weather ticks once');
 g=game(system);g.team[0][0].hp=0;g.team[0][1].hp=0;H.refreshBattleOutcome(g);eq(H.replacementSlots(g,0),[0,1],'Both fainted positions require replacement');const foeHp=g.team[1].map(x=>x.hp);resolve(g,D({kind:'switch',index:2},{kind:'switch',index:3}),P);eq(g.turn,1,'Replacement consumes no combat round');eq(g.activeSlots[0],[2,3],'Both reserves enter their chosen positions');eq(g.team[1].map(x=>x.hp),foeHp,'No free incoming hit during replacement');
 g=game(system,0);g.team[0][0].hp=0;H.refreshBattleOutcome(g);eq(g.winner,null,'A surviving partner keeps trainer in game');eq(H.replacementSides(g),[false,false],'No replacement when no reserve remains');resolve(g,D(P,A('Tackle',1,0)));ok(g.team[1][0].hp<1000,'Surviving partner continues taking actions');g.team[0][1].hp=0;H.refreshBattleOutcome(g);eq(g.winner,1,'Only entire-team defeat ends battle');
 for(const bad of [D({kind:'switch',index:2},{kind:'switch',index:2}),D({kind:'switch',index:1},P),D(A('Tackle',1,99),P),D(A('Tackle'),{kind:'move',moveId:'missing'})]){g=game(system);const before=JSON.stringify(g);throws(()=>H.resolve(g,bad,D()),'Invalid bundles rejected');eq(JSON.stringify(g),before,'Invalid bundle has no partial mutations');}
 g=game(system);resolve(g,D(A('U-turn',1,0),P));eq(g.activeSlots[0][0],2,'Pivot chooses genuine reserve');eq(g.activeSlots[0][1],1,'Pivot leaves partner in place');
 g=game(system);resolve(g,D(A('Sucker Punch',1,1),P),D(A('Tackle',0,0),A('Growl',0,0)));eq(g.team[1][1].hp,1000,'Sucker Punch checks selected target’s action');ok(g.log.some(x=>x.text.includes('Sucker Punch falhou:')),'Failure is logged');
 g=game(system);resolve(g,D(A('Sucker Punch',1,1),P),D(A('Growl',0,0),A('Tackle',0,0)));ok(g.team[1][1].hp<1000,'Selected attacking target qualifies for Sucker Punch');
 g=game(system);resolve(g,D(A('Ally Switch'),A('Tackle',1,0)));eq(g.activeSlots[0],[1,0],'Ally Switch swaps occupied positions');ok(g.team[1][0].hp<1000,'Partner retains its queued action after Ally Switch');
 g=game(system);resolve(g,D(A('After You',0,1),A('Tackle',1,0)),D(A('Tackle',0,0),P));eq(g.visualEvents.filter(x=>x.kind==='move').map(x=>x.name),['After You','Tackle','Tackle'],'After You moves partner command immediately after the user');
 g=game(system);resolve(g,D(A('Quash',1,0),A('Tackle',1,0)),D(A('Tackle',0,0),A('Tackle',0,0)));eq(g.visualEvents.filter(x=>x.kind==='move').map(x=>x.side+":"+x.slot),['0:0','0:1','1:1','1:0'],'Quash moves selected target command to end of round');
 g=game(system);resolve(g,D(A('Follow Me'),P),D(P,A('Tackle',0,1)));ok(g.team[0][0].hp<1000,'Follow Me attracts a directed enemy move');eq(g.team[0][1].hp,1000,'Original target protected by redirection');
 g=game(system);g.team[0][1].hp=400;resolve(g,D(A('Heal Pulse',0,1),P));eq(g.team[0][1].hp,900,'Targeted ally healing works');eq(g.team[1][0].hp,1000,'Ally heal does not heal enemy');
 g=game(system);for(const x of H.battlerEntries(g))x.pokemon.effects.push({stat:'atk',delta:2,remaining:null,source:'test'});resolve(g,D(A('Haze'),P));for(const x of H.battlerEntries(g))eq(H.stages(x.pokemon,'atk'),0,'Haze affects all four');
 g=game(system);resolve(g,D(A('Perish Song'),P));for(const x of H.battlerEntries(g))eq(x.pokemon.flags.fx.perishsong.count,3,'Perish Song starts on all four');
 g=game(system);resolve(g,D(A('Spikes'),P));g.team[1][0].hp=0;H.refreshBattleOutcome(g);resolve(g,P,D({kind:'switch',index:2},P));ok(g.team[1][2].hp<1000,'Hazards affect reserve entering the fainted position');eq(g.team[1][1].hp,1000,'Partner already in field does not retrigger hazards');
 g=game(system);const wire=JSON.parse(JSON.stringify(g));resolve(wire,D(A('Tackle',1,1),P));ok(wire.team[1][1].hp<1000,'Serialized online battle retains target/slot behavior');
}
throws(()=>H.newGame([mon('one')],[mon('two')],{format:'doubles'}),'Need at least two Pokémon per side');
console.log(checks+' doubles assertions passed in both damage modes.');
