const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8'),blocks=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)],data=Object.fromEntries(blocks.filter(b=>/application\/json/.test(b[1])).map(b=>[b[1].match(/id="([^"]+)"/)[1],b[2]]));
for(const b of blocks)if(!/type=|src=/.test(b[1]))new vm.Script(b[2]);
const ctx={document:{getElementById:id=>({textContent:data[id]})},structuredClone,Math:Object.create(Math),module:{exports:{}}};ctx.Math.random=()=>.5;vm.runInNewContext(blocks.find(b=>b[2].includes('const HH = (() =>'))[2],ctx);const H=ctx.module.exports,SD=JSON.parse(data.smogonSnapshot);let count=0,serial=0;
const eq=(a,b,label)=>{assert.deepStrictEqual(JSON.parse(JSON.stringify(a)),JSON.parse(JSON.stringify(b)),label);count++},ok=(v,label)=>{assert(v,label);count++};
const move=name=>{const d=SD.moves[H.normalizeName(name)];return {id:H.normalizeName(name),name:d.name,type:d.type,category:d.category,power:d.basePower,accuracy:90,alwaysHits:true,active:true}};
const mon=(names=['Tackle'],props={})=>({id:'hazard-test-'+(++serial),name:'Tester',type1:'Normal',level:36,maxHp:400,stats:{hp:400,atk:100,def:100,spa:100,spd:100,spe:100},moves:names.map(move),...props});
const P={kind:'pass'},A=n=>({kind:'move',moveId:H.normalizeName(n)}),S=i=>({kind:'switch',index:i});
function game(names,system,props={},enemyProps={}){return H.newGame([mon(names,props),mon(),mon()],[mon(['Tackle','Protect','Substitute'],enemyProps),mon(),mon()],{damageSystem:system});}
for(const system of ['standard','matrix-v0.2']){
 let g=game(['Spikes','Toxic Spikes','Stealth Rock','Sticky Web'],system);for(const n of ['Spikes','Toxic Spikes','Stealth Rock','Sticky Web'])H.resolve(g,A(n),P);eq(g.hazards[1],{spikes:1,toxicSpikes:1,stealthRock:1,stickyWeb:1},'four hazards placed');eq(H.active(g,1).hp,400,'no immediate damage');eq(H.active(g,1).status,null,'no immediate poison');eq(H.effStat(H.active(g,1),'spe'),100,'no immediate Web penalty');
 H.resolve(g,A('Spikes'),P);H.resolve(g,A('Spikes'),P);H.resolve(g,A('Spikes'),P);eq(g.hazards[1].spikes,3,'Spikes cap');ok(g.log.some(x=>x.text.includes('já está no limite')),'cap failure logged');H.resolve(g,A('Toxic Spikes'),P);H.resolve(g,A('Toxic Spikes'),P);eq(g.hazards[1].toxicSpikes,2,'Toxic Spikes cap');
 H.switchTo(g,1,1);eq(H.active(g,1).hp,380,'3d6 Spikes plus 2d6 Rock; no stat or level bonus');eq(H.active(g,1).status.id,'toxic','2 layers inflict Toxic');eq(H.effStat(H.active(g,1),'spe'),75,'Web is exact 25%');eq(H.stages(H.active(g,1),'spe'),0,'Web not misrepresented as stat stage');ok(H.specialEffectLabels(g,H.active(g,1)).some(x=>x.includes('Sticky Web')),'Web condition shown');eq(H.hazardSummary(g,1).length,4,'all hazard indicators');
 g=game(['Sticky Web'],system);g.hazards[1]={stickyWeb:1};H.switchTo(g,1,1);for(let i=0;i<5;i++)H.resolve(g,P,P);eq(H.effStat(H.active(g,1),'spe'),75,'Web persists past 3 rounds');H.switchTo(g,1,2);H.switchTo(g,1,1);eq(H.effStat(H.active(g,1),'spe'),75,'Web does not stack on reentry');H.switchTo(g,1,2);eq(H.effStat(g.team[1][1],'spe'),100,'Web cleared on leaving');
 for(const [ability,type,item]of [['Levitate','Normal',''],['Eelevate','Normal',''],['','Flying',''],['','Normal','Air Balloon']]){g=game(['Spikes'],system);Object.assign(g.team[1][1],{abilityName:ability,types:[type],baseTypes:[type],heldItem:item});g.hazards[1]={spikes:3,toxicSpikes:2,stickyWeb:1};H.switchTo(g,1,1);eq(H.active(g,1).hp,400,'airborne avoids Spikes');eq(H.active(g,1).status,null,'airborne avoids Toxic Spikes');eq(H.effStat(H.active(g,1),'spe'),100,'airborne avoids Web');}
 g=game(['Spikes'],system);g.team[1][1].types=g.team[1][1].baseTypes=['Flying'];g.team[1][1].heldItem='Iron Ball';g.hazards[1]={spikes:1};H.switchTo(g,1,1);eq(H.active(g,1).hp,396,'Iron Ball grounds Flying');
 g=game(['Gravity'],system);H.resolve(g,A('Gravity'),P);g.team[1][1].abilityName='Levitate';g.hazards[1]={spikes:1};H.switchTo(g,1,1);eq(H.active(g,1).hp,396,'Gravity grounds Levitate');
 for(const [types,amount]of [[['Fire','Flying'],16],[['Normal'],8],[['Fighting'],4],[['Fighting','Steel'],4]]){g=game(['Stealth Rock'],system);g.team[1][1].types=g.team[1][1].baseTypes=types;g.hazards[1]={stealthRock:1};H.switchTo(g,1,1);eq(H.active(g,1).hp,400-amount,'Rock uses RPG weakness dice and minimum 1d6');}
 g=game(['Spikes'],system);g.team[1][1].heldItem='Heavy-Duty Boots';g.hazards[1]={spikes:3,toxicSpikes:2,stealthRock:1,stickyWeb:1};H.switchTo(g,1,1);eq(H.active(g,1).hp,400,'Boots prevent all hazard damage');eq(H.active(g,1).status,null,'Boots prevent poison');eq(H.effStat(H.active(g,1),'spe'),100,'Boots prevent Web');eq(Object.keys(g.hazards[1]).length,4,'Boots do not remove hazards');
 g.team[1][2].types=g.team[1][2].baseTypes=['Poison'];g.team[1][2].heldItem='Heavy-Duty Boots';H.switchTo(g,1,2);ok(!g.hazards[1].toxicSpikes,'grounded Poison still absorbs Toxic Spikes wearing Boots');
 g=game(['Magic Room'],system);H.resolve(g,A('Magic Room'),P);g.team[1][1].heldItem='Heavy-Duty Boots';g.hazards[1]={spikes:1};H.switchTo(g,1,1);eq(H.active(g,1).hp,396,'Magic Room suppresses Boots');
 g=game(['Spikes'],system);g.team[1][1].abilityName='Magic Guard';g.hazards[1]={spikes:3,stealthRock:1,toxicSpikes:1,stickyWeb:1};H.switchTo(g,1,1);eq(H.active(g,1).hp,400,'Magic Guard prevents damage');eq(H.active(g,1).status.id,'poison','Magic Guard still permits poison');eq(H.effStat(H.active(g,1),'spe'),75,'Magic Guard still permits Web');eq(H.stages(H.active(g,1),'spd'),1,'Magic Guard bonus once per round');
 g=game(['Spikes'],system);g.team[1][1].types=g.team[1][1].baseTypes=['Steel'];g.hazards[1]={toxicSpikes:2};H.switchTo(g,1,1);eq(H.active(g,1).status,null,'Steel poison immunity');eq(g.hazards[1].toxicSpikes,2,'Steel does not absorb layers');
 g=game(['Spikes'],system);g.team[1][1].abilityName='Defiant';g.hazards[1]={stickyWeb:1};H.switchTo(g,1,1);eq(H.stages(H.active(g,1),'atk'),0,'field Defiant delayed');H.resolve(g,P,P);H.resolve(g,P,P);eq(H.stages(H.active(g,1),'atk'),2,'Defiant next-round bonus');
 g=game(['Spikes'],system);g.team[1][1].abilityName='Competitive';g.hazards[1]={stickyWeb:1};H.switchTo(g,1,1);eq(H.stages(H.active(g,1),'spa'),3,'Competitive rework for Speed drop');
 for(const ability of ['Slipstream','Limber','White Smoke','Full Metal Body']){g=game(['Spikes'],system);g.team[1][1].abilityName=ability;g.hazards[1]={stickyWeb:1};H.switchTo(g,1,1);eq(H.effStat(H.active(g,1),'spe'),100,ability+' prevents Web');}
 g=game(['Spikes'],system);g.team[1][1].abilityName='Contrary';g.hazards[1]={stickyWeb:1};H.switchTo(g,1,1);eq(H.effStat(H.active(g,1),'spe'),125,'Contrary inverts Web percentage');
 g=game(['Spikes'],system);g.team[1][1].heldItem='White Herb';g.hazards[1]={stickyWeb:1};H.switchTo(g,1,1);eq(H.effStat(H.active(g,1),'spe'),100,'White Herb removes Web penalty');eq(H.active(g,1).heldItem,'','Herb consumed');
 for(const ability of ['Healer','Pastel Veil','Purifying Salt','Comatose','Shields Down']){g=game(['Toxic Spikes'],system);g.team[1][1].abilityName=ability;g.hazards[1]={toxicSpikes:2};H.switchTo(g,1,1);eq(H.active(g,1).status,null,ability+' prevents hazard Toxic');}
 g=game(['Spikes'],system);g.team[1][1].abilityName='Immunity';g.team[1][1].hp=200;g.hazards[1]={toxicSpikes:2};H.switchTo(g,1,1);eq(H.active(g,1).hp,204,'Immunity heals when blocking hazard poison');
 g=game(['Earthquake'],system,{abilityName:'Mold Breaker'},{heldItem:'Air Balloon'});H.resolve(g,A('Earthquake'),P);eq(H.active(g,1).hp,400,'Mold Breaker does not bypass item-based levitation');
 g=game(['Tackle'],system,{}, {heldItem:'Air Balloon'});H.resolve(g,A('Tackle'),P);eq(H.active(g,1).heldItem,'','direct hit bursts Air Balloon');
 g=game(['Spikes'],system);g.team[1][1].heldItem='Air Balloon';g.hazards[1]={stealthRock:1};H.switchTo(g,1,1);eq(H.active(g,1).heldItem,'Air Balloon','indirect Rock hazard does not burst balloon');
 g=game(['Spikes'],system);g.team[1][1].heldItem='Iron Ball';H.switchTo(g,1,1);eq(H.effStat(H.active(g,1),'spe'),50,'Iron Ball halves Speed');
 g=game(['Spikes'],system);H.active(g,1).flags.substitute=100;H.resolve(g,A('Spikes'),A('Protect'));eq(g.hazards[1].spikes,1,'side hazard bypasses Protect and Substitute');
 g=game(['Spikes'],system,{}, {abilityName:'Magic Bounce'});H.resolve(g,A('Spikes'),P);eq(g.hazards[1].spikes,1,'book Magic Bounce does not reflect field hazards');eq(g.hazards[0],{},'no field bounce');H.active(g,1).flags.fx={magiccoat:{started:g.turn,until:g.turn}};H.resolve(g,A('Spikes'),P);eq(g.hazards[0].spikes,1,'Magic Coat reflects field hazard');
 for(const n of ['Ceaseless Edge','Stone Axe']){g=game([n],system);H.active(g,1).flags.substitute=100;H.resolve(g,A(n),P);eq(g.hazards[1][n==='Stone Axe'?'stealthRock':'spikes'],1,'signature hazard applied through Substitute');}
 g=game(['Ceaseless Edge'],system);H.active(g,1).types=['Fairy'];H.active(g,1).stats.def=9999;H.resolve(g,A('Ceaseless Edge'),P);eq(g.hazards[1].spikes,1,'hazard on connected hit fully reduced by defenses');
 for(const n of ['Rapid Spin','Mortal Spin']){g=game([n],system);g.hazards[0]={spikes:3,toxicSpikes:2,stealthRock:1,stickyWeb:1};H.active(g,0).flags.fx={leechseed:{sourceSide:1},partiallytrapped:{sourceId:H.active(g,1).id,sourceSide:1}};H.active(g,1).flags.substitute=100;H.resolve(g,A(n),P);eq(g.hazards[0],{},'spin cleans through Substitute');ok(!H.active(g,0).flags.fx.leechseed&&!H.active(g,0).flags.fx.partiallytrapped,'spin clears seed and partial trap');if(n==='Rapid Spin')eq(H.stages(H.active(g,0),'spe'),1,'Rapid Spin boosts Speed');}
 for(const [n,type]of [['Rapid Spin','Ghost'],['Mortal Spin','Steel']]){g=game([n],system,{}, {type1:type});g.hazards[0]={spikes:2};H.resolve(g,A(n),P);eq(g.hazards[0].spikes,2,'immune target prevents spin cleanup');}
 g=game(['Rapid Spin'],system);g.hazards[0]={spikes:2};H.resolve(g,A('Rapid Spin'),A('Protect'));eq(g.hazards[0].spikes,2,'Protect prevents cleanup');
 g=game(['Mortal Spin'],system);g.hazards[0]={spikes:1};H.resolve(g,A('Mortal Spin'),P);eq(H.active(g,1).status.id,'poison','Mortal Spin poison secondary');eq(g.hazards[0],{},'Mortal Spin clears own hazards');
 g=game(['Defog'],system);g.hazards=[{spikes:3},{spikes:2,stickyWeb:1}];g.screens[1]={reflect:{turns:3,level:36}};H.resolve(g,A('Defog'),P);eq(g.hazards[1],{},'book Defog clears enemy side');eq(g.hazards[0],{spikes:3},'book Defog preserves own side');eq(g.screens[1],{},'Defog clears enemy screen');
 g=game(['Tidy Up'],system);g.hazards=[{spikes:3},{toxicSpikes:2}];H.active(g,1).flags.substitute=100;H.resolve(g,A('Tidy Up'),P);eq(g.hazards,[{},{}],'Tidy Up clears both sides');ok(!H.active(g,1).flags.substitute,'Tidy Up removes Substitute');eq(H.stages(H.active(g,0),'atk'),1,'Tidy Up boosts Attack');
 g=game(['Court Change'],system);g.hazards=[{spikes:3},{stickyWeb:1}];const hp=H.active(g,0).hp;H.resolve(g,A('Court Change'),P);eq(g.hazards,[{stickyWeb:1},{spikes:3}],'Court Change swaps hazards');eq(H.active(g,0).hp,hp,'swapping hazards does not trigger them');eq(H.effStat(H.active(g,0),'spe'),100,'swapped Web does not affect already-active Pokémon');
 g=game(['Tackle'],system,{}, {abilityName:'Toxic Debris'});H.resolve(g,A('Tackle'),P);eq(g.hazards[0].toxicSpikes,1,'Toxic Debris first layer');H.resolve(g,A('Tackle'),P);eq(g.hazards[0].toxicSpikes,2,'Toxic Debris second layer');eq(H.active(g,0).status.id,'poison','second layer poisons triggering attacker');
 g=game(['Earthquake'],system,{}, {abilityName:'Earth Eater'});g.hazards[1]={spikes:2,toxicSpikes:2,stickyWeb:1,stealthRock:1};H.active(g,1).hp=200;H.resolve(g,A('Earthquake'),P);eq(H.active(g,1).hp,300,'Earth Eater heals quarter HP');eq(g.hazards[1],{stealthRock:1},'Earth Eater clears only ground hazards');
 // A KO caused by entry hazards requires another replacement without a round tick or free attack.
 g=game(['Spikes'],system);g.hazards[1]={spikes:1};H.damage(g,H.active(g,1),9999,'KO fixture');g.needSwitch[1]=true;g.team[1][1].hp=1;const turn=g.turn,our=JSON.stringify(H.active(g,0));H.resolve(g,P,S(1));eq(H.active(g,1).hp,0,'entry hazard can KO incoming reserve');eq(g.turn,turn,'hazard KO does not advance replacement round');eq(JSON.stringify(H.active(g,0)),our,'opponent unchanged during replacement');ok(g.needSwitch[1],'another reserve required');H.resolve(g,P,S(2));eq(H.active(g,1).hp,396,'next reserve takes hazards once');eq(g.turn,turn,'second replacement also no free action');
 eq(JSON.parse(JSON.stringify(g)).hazards,g.hazards,'hazard state serializable');
}
console.log(`${count} hazard assertions passed in standard and experimental damage modes.`);
